<?php

namespace ContainerXLRsZdm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Bmf2sqXService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Bmf2sqX' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Bmf2sqX'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\ReclamationController::barChartData' => ['privates', '.service_locator.bvmeD74', 'get_ServiceLocator_BvmeD74Service', true],
            'App\\Controller\\ReclamationController::data' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\ReclamationController::deleteReclamation' => ['privates', '.service_locator.GQZbvNR', 'get_ServiceLocator_GQZbvNRService', true],
            'App\\Controller\\ReclamationController::deleteReclamationAdmin' => ['privates', '.service_locator.GQZbvNR', 'get_ServiceLocator_GQZbvNRService', true],
            'App\\Controller\\ReclamationController::deleteReponse' => ['privates', '.service_locator.GQZbvNR', 'get_ServiceLocator_GQZbvNRService', true],
            'App\\Controller\\ReclamationController::deleteReponsea' => ['privates', '.service_locator.GQZbvNR', 'get_ServiceLocator_GQZbvNRService', true],
            'App\\Controller\\ReclamationController::editReclamation' => ['privates', '.service_locator.GQZbvNR', 'get_ServiceLocator_GQZbvNRService', true],
            'App\\Controller\\ReclamationController::filterReclamations' => ['privates', '.service_locator.C6Hmyfu', 'get_ServiceLocator_C6HmyfuService', true],
            'App\\Controller\\ReclamationController::firstLineChartData' => ['privates', '.service_locator.bvmeD74', 'get_ServiceLocator_BvmeD74Service', true],
            'App\\Controller\\ReclamationController::index' => ['privates', '.service_locator.GyY0RxJ', 'get_ServiceLocator_GyY0RxJService', true],
            'App\\Controller\\ReclamationController::indexRepnse' => ['privates', '.service_locator.kSOHbON', 'get_ServiceLocator_KSOHbONService', true],
            'App\\Controller\\ReclamationController::listReclamations' => ['privates', '.service_locator.C6Hmyfu', 'get_ServiceLocator_C6HmyfuService', true],
            'App\\Controller\\ReclamationController::listReclamationsDESC' => ['privates', '.service_locator.C6Hmyfu', 'get_ServiceLocator_C6HmyfuService', true],
            'App\\Controller\\ReclamationController::listUserReclamations' => ['privates', '.service_locator.C6Hmyfu', 'get_ServiceLocator_C6HmyfuService', true],
            'App\\Controller\\ReclamationController::saveRec' => ['privates', '.service_locator.GQZbvNR', 'get_ServiceLocator_GQZbvNRService', true],
            'App\\Controller\\ReclamationController::searchconv' => ['privates', '.service_locator.C6Hmyfu', 'get_ServiceLocator_C6HmyfuService', true],
            'App\\Controller\\ReclamationController::searchconvuser' => ['privates', '.service_locator.C6Hmyfu', 'get_ServiceLocator_C6HmyfuService', true],
            'App\\Controller\\ReclamationController::secondLineChartData' => ['privates', '.service_locator.bvmeD74', 'get_ServiceLocator_BvmeD74Service', true],
            'App\\Controller\\ReclamationController::updateMessage' => ['privates', '.service_locator.GQZbvNR', 'get_ServiceLocator_GQZbvNRService', true],
            'App\\Controller\\ReclamationController::updateMessageuser' => ['privates', '.service_locator.GQZbvNR', 'get_ServiceLocator_GQZbvNRService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Controller\\ReclamationController:barChartData' => ['privates', '.service_locator.bvmeD74', 'get_ServiceLocator_BvmeD74Service', true],
            'App\\Controller\\ReclamationController:data' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\ReclamationController:deleteReclamation' => ['privates', '.service_locator.GQZbvNR', 'get_ServiceLocator_GQZbvNRService', true],
            'App\\Controller\\ReclamationController:deleteReclamationAdmin' => ['privates', '.service_locator.GQZbvNR', 'get_ServiceLocator_GQZbvNRService', true],
            'App\\Controller\\ReclamationController:deleteReponse' => ['privates', '.service_locator.GQZbvNR', 'get_ServiceLocator_GQZbvNRService', true],
            'App\\Controller\\ReclamationController:deleteReponsea' => ['privates', '.service_locator.GQZbvNR', 'get_ServiceLocator_GQZbvNRService', true],
            'App\\Controller\\ReclamationController:editReclamation' => ['privates', '.service_locator.GQZbvNR', 'get_ServiceLocator_GQZbvNRService', true],
            'App\\Controller\\ReclamationController:filterReclamations' => ['privates', '.service_locator.C6Hmyfu', 'get_ServiceLocator_C6HmyfuService', true],
            'App\\Controller\\ReclamationController:firstLineChartData' => ['privates', '.service_locator.bvmeD74', 'get_ServiceLocator_BvmeD74Service', true],
            'App\\Controller\\ReclamationController:index' => ['privates', '.service_locator.GyY0RxJ', 'get_ServiceLocator_GyY0RxJService', true],
            'App\\Controller\\ReclamationController:indexRepnse' => ['privates', '.service_locator.kSOHbON', 'get_ServiceLocator_KSOHbONService', true],
            'App\\Controller\\ReclamationController:listReclamations' => ['privates', '.service_locator.C6Hmyfu', 'get_ServiceLocator_C6HmyfuService', true],
            'App\\Controller\\ReclamationController:listReclamationsDESC' => ['privates', '.service_locator.C6Hmyfu', 'get_ServiceLocator_C6HmyfuService', true],
            'App\\Controller\\ReclamationController:listUserReclamations' => ['privates', '.service_locator.C6Hmyfu', 'get_ServiceLocator_C6HmyfuService', true],
            'App\\Controller\\ReclamationController:saveRec' => ['privates', '.service_locator.GQZbvNR', 'get_ServiceLocator_GQZbvNRService', true],
            'App\\Controller\\ReclamationController:searchconv' => ['privates', '.service_locator.C6Hmyfu', 'get_ServiceLocator_C6HmyfuService', true],
            'App\\Controller\\ReclamationController:searchconvuser' => ['privates', '.service_locator.C6Hmyfu', 'get_ServiceLocator_C6HmyfuService', true],
            'App\\Controller\\ReclamationController:secondLineChartData' => ['privates', '.service_locator.bvmeD74', 'get_ServiceLocator_BvmeD74Service', true],
            'App\\Controller\\ReclamationController:updateMessage' => ['privates', '.service_locator.GQZbvNR', 'get_ServiceLocator_GQZbvNRService', true],
            'App\\Controller\\ReclamationController:updateMessageuser' => ['privates', '.service_locator.GQZbvNR', 'get_ServiceLocator_GQZbvNRService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
        ], [
            'App\\Controller\\ReclamationController::barChartData' => '?',
            'App\\Controller\\ReclamationController::data' => '?',
            'App\\Controller\\ReclamationController::deleteReclamation' => '?',
            'App\\Controller\\ReclamationController::deleteReclamationAdmin' => '?',
            'App\\Controller\\ReclamationController::deleteReponse' => '?',
            'App\\Controller\\ReclamationController::deleteReponsea' => '?',
            'App\\Controller\\ReclamationController::editReclamation' => '?',
            'App\\Controller\\ReclamationController::filterReclamations' => '?',
            'App\\Controller\\ReclamationController::firstLineChartData' => '?',
            'App\\Controller\\ReclamationController::index' => '?',
            'App\\Controller\\ReclamationController::indexRepnse' => '?',
            'App\\Controller\\ReclamationController::listReclamations' => '?',
            'App\\Controller\\ReclamationController::listReclamationsDESC' => '?',
            'App\\Controller\\ReclamationController::listUserReclamations' => '?',
            'App\\Controller\\ReclamationController::saveRec' => '?',
            'App\\Controller\\ReclamationController::searchconv' => '?',
            'App\\Controller\\ReclamationController::searchconvuser' => '?',
            'App\\Controller\\ReclamationController::secondLineChartData' => '?',
            'App\\Controller\\ReclamationController::updateMessage' => '?',
            'App\\Controller\\ReclamationController::updateMessageuser' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\ReclamationController:barChartData' => '?',
            'App\\Controller\\ReclamationController:data' => '?',
            'App\\Controller\\ReclamationController:deleteReclamation' => '?',
            'App\\Controller\\ReclamationController:deleteReclamationAdmin' => '?',
            'App\\Controller\\ReclamationController:deleteReponse' => '?',
            'App\\Controller\\ReclamationController:deleteReponsea' => '?',
            'App\\Controller\\ReclamationController:editReclamation' => '?',
            'App\\Controller\\ReclamationController:filterReclamations' => '?',
            'App\\Controller\\ReclamationController:firstLineChartData' => '?',
            'App\\Controller\\ReclamationController:index' => '?',
            'App\\Controller\\ReclamationController:indexRepnse' => '?',
            'App\\Controller\\ReclamationController:listReclamations' => '?',
            'App\\Controller\\ReclamationController:listReclamationsDESC' => '?',
            'App\\Controller\\ReclamationController:listUserReclamations' => '?',
            'App\\Controller\\ReclamationController:saveRec' => '?',
            'App\\Controller\\ReclamationController:searchconv' => '?',
            'App\\Controller\\ReclamationController:searchconvuser' => '?',
            'App\\Controller\\ReclamationController:secondLineChartData' => '?',
            'App\\Controller\\ReclamationController:updateMessage' => '?',
            'App\\Controller\\ReclamationController:updateMessageuser' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
