<?php

namespace ContainerC3ckZRu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_KSOHbONService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.kSOHbON' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.kSOHbON'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'RecRepo' => ['privates', 'App\\Repository\\ReclamationRepository', 'getReclamationRepositoryService', true],
            'doctrine' => ['services', 'doctrine', 'getDoctrineService', false],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'RecRepo' => 'App\\Repository\\ReclamationRepository',
            'doctrine' => '?',
            'entityManager' => '?',
        ]);
    }
}
