<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTDa5Jfk\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTDa5Jfk/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTDa5Jfk.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTDa5Jfk\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerTDa5Jfk\App_KernelDevDebugContainer([
    'container.build_hash' => 'TDa5Jfk',
    'container.build_id' => 'bc05e54a',
    'container.build_time' => 1713498508,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTDa5Jfk');
