<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWTvvuA3\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWTvvuA3/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWTvvuA3.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWTvvuA3\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWTvvuA3\App_KernelDevDebugContainer([
    'container.build_hash' => 'WTvvuA3',
    'container.build_id' => '5aebf989',
    'container.build_time' => 1714175050,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWTvvuA3');
