<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container2lSe5nY\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container2lSe5nY/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container2lSe5nY.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container2lSe5nY\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container2lSe5nY\App_KernelDevDebugContainer([
    'container.build_hash' => '2lSe5nY',
    'container.build_id' => '9b6e2973',
    'container.build_time' => 1712110317,
], __DIR__.\DIRECTORY_SEPARATOR.'Container2lSe5nY');
